FROM node:24-alpine AS deps
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install

FROM node:24-alpine AS builder
WORKDIR /app
ARG NEXT_PUBLIC_SITE_URL=http://localhost:3000
ARG NEXT_PUBLIC_SUPPORT_EMAIL=support@example.com
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT=
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT=
ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SUPPORT_EMAIL=$NEXT_PUBLIC_SUPPORT_EMAIL
ENV NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT=$NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT
ENV NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT=$NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:24-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT=
ARG NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT=
ENV NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT=$NEXT_PUBLIC_GOOGLE_ADSENSE_CLIENT
ENV NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT=$NEXT_PUBLIC_GOOGLE_ADSENSE_SLOT

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

EXPOSE 3000
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 CMD node -e "fetch('http://127.0.0.1:3000/api/health').then((r)=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"
CMD ["sh", "-c", "HOSTNAME=0.0.0.0 node server.js"]
