import type { Metadata } from "next";
import { ConverterClient } from "@/components/converter/ConverterClient";

export const metadata: Metadata = {
  title: "PDF Statement Converter",
  description:
    "Upload one financial statement PDF, review extracted rows, edit them, and download Excel or CSV with local-first processing.",
  alternates: {
    canonical: "/converter"
  }
};

export default function ConverterPage() {
  return (
    <main className="converter-shell">
      <section className="hero" style={{ marginBottom: 32 }}>
        <div>
          <h1>PDF Statement Converter</h1>
          <p>
            Upload a bank or credit card statement and download an Excel file generated by the self-hosted server-side conversion engine. Text PDFs use table extraction, and scanned PDFs fall back to OCR.
          </p>
        </div>
        <div className="notice good">
          No account is required. Files are processed temporarily by your server-side converter and deleted after the conversion request finishes.
        </div>
      </section>
      <ConverterClient />
    </main>
  );
}
